use shell;
create table Romeo (pr_id int primary key , pr_name text , Total_marks int, location text not null );
insert into Romeo values(101,"Aman",900,"lko");
insert into Romeo values(102,"Vishal",600,"lko");
insert into Romeo values(103,"Rahul",780,"DEL");
insert into Romeo values(104,"Nitish",982,"lko");
insert into Romeo values(105,"Rohit",800,"lko");
insert into Romeo values(106,"Suresh",456,"DEL");
insert into Romeo values(107,"Nilesh",380,"BLR");
insert into Romeo values(108,"Mohit",700,"BLR");
insert into Romeo values(109,"koustubh",875,"KOL");
insert into Romeo values(110,"Zeeshan",900,"lko");
SELECT*FROM romeo;
SELECT *, dense_rank() OVER(ORDER BY total_MARKS DESC)  FROM Romeo ;
select *, rank() over(order by total_marks desc ) from romeo ;
select *, row_number() over(order by total_marks desc ) from romeo ;

SELECT *, dense_rank() OVER(partition by location order BY total_MARKS DESC)  FROM Romeo ;
create view zoho as select pr_name ,total_marks,location from romeo;
select*from zoho;
create index zohotra on romeo (total_marks) ;
show index from romeo;

update  romeo set total_marks = 998 where pr_id = 101; 
select*from romeo;
alter table romeo  modify pr_name varchar(50);
alter table romeo  add column emp_no int not null;
select*from romeo;
update romeo set emp_no = 01 where pr_id=101;
update romeo set emp_no = 02 where pr_id=102;
update romeo set emp_no = 03 where pr_id=103;
update romeo set emp_no = 04 where pr_id=104;
update romeo set emp_no = 05 where pr_id=105;
update romeo set emp_no = 06 where pr_id=106;
update romeo set emp_no = 07 where pr_id=107;
update romeo set emp_no = 08 where pr_id=108;
update romeo set emp_no = 09 where pr_id=109;
update romeo set emp_no = 10 where pr_id=110;

select*from romeo;
alter table romeo add column Dept_name varchar(50);
update romeo set Dept_name ="IT" where pr_id=101;
update romeo set Dept_name ="FIN" where pr_id=102;
update romeo set Dept_name ="IT" where pr_id=103;
update romeo set Dept_name ="IT" where pr_id=104;
update romeo set Dept_name ="HR" where pr_id=105;
update romeo set Dept_name ="HR" where pr_id=106;
update romeo set Dept_name ="FIN" where pr_id=107;
update romeo set Dept_name ="CR" where pr_id=108;
update romeo set Dept_name ="CR" where pr_id=109;
update romeo set Dept_name ="IT" where pr_id=110;
SELECT*FROM ROMEO;
select Dept_name ,count(Dept_name ) ,sum(total_marks),avg(total_marks)     from romeo group by Dept_name having count(Dept_name)>1;
select*from romeo order by total_marks desc limit 2,1;    
